# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a639a97723e94fe304b6128006b361e93699df1475a6b7dbf9b7e94eddd3ee8c51274d110e7773838b1ae4984a1368d4d497d8cc7a431d2326d4bf0cbe4c928

test:
  secret_key_base: e50ef2f5b2d92853ff5fc53658bdb2527b27ac6e92105dd885ab3833198d0f2f001c9498c864de3bccbd83c193e7d43d68853afcf1767b6e5f62d704912d6c68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
